spring:
  application.name: storage
  jmx.enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: storage
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false

server.port: 10001

eureka:
  instance:
    hostname: storage
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: '*'
